stages:
  - build
  - release

release:
  stage: release
  only:
    - tags
  image:
    name: docker.io/goreleaser/goreleaser-cross:v1.21
    entrypoint: ['']
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release
