stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser-cross:v1.21
    entrypoint: ['']
  only:
    - tags
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
