stages:
  - build
  - release

build:
  stage: build
  image: docker.io/golang:1.20
  script:
    - go build
  artifacts:
    paths:
      - ./mb2osm
    expire_in: 1 hour

release:
  stage: release
  only:
    - tags
  image:
    name: docker.io/goreleaser/goreleaser-cross:v1.21
    entrypoint: ['']
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release
