stages:
  - test
  - release

test:
  stage: test
  image:
    name: docker.io/golang:1.23
  script:
    - go test ./...

release:
  stage: release
  only:
    - tags
  image:
    name: docker.io/goreleaser/goreleaser-cross:v1.23
    entrypoint: ['']
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release
