version: 2

builds:
  - binary: mb2osm
    main: cmd/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - android
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      # we only need the arm64 build on android
      - goos: android
        goarch: amd64
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.buildTime={{.Date}}

archives:
  - name_template: "mb2osm_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
gitlab_urls:
  use_package_registry: true
snapshot:
  version_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# # The following config was used for bundling the SQLite
# # C library and using the mattn/go-sqlite3 bindings.
# # The binding were replaced by modernc.org/sqlite.

# env:
# - CGO_ENABLED=1

# builds:
#   # MacOS AMD64
#   - id: mb2osm-darwin-amd64
#     binary: mb2osm
#     main: cmd/main.go
#     goarch:
#       - amd64
#     goos:
#       - darwin
#     env:
#       - CC=o64-clang
#       - CXX=o64-clang++
#     flags:
#       - -trimpath

#   # MacOS ARM64
#   - id: mb2osm-darwin-arm64
#     binary: mb2osm
#     main: cmd/main.go
#     goarch:
#       - arm64
#     goos:
#       - darwin
#     env:
#       - CC=oa64-clang
#       - CXX=oa64-clang++
#     flags:
#       - -trimpath

#   # Linux AMD64
#   - id: mb2osm-linux-amd64
#     binary: mb2osm
#     main: cmd/main.go
#     env:
#       - CC=x86_64-linux-gnu-gcc
#       - CXX=x86_64-linux-gnu-g++
#     goarch:
#       - amd64
#     goos:
#       - linux
#     flags:
#       - -trimpath
#     ldflags:
#       - -extldflags "-lc -lrt -lpthread --static"

#   # Linux ARM64
#   - id: mb2osm-linux-arm64
#     binary: mb2osm
#     main: cmd/main.go
#     goarch:
#       - arm64
#     goos:
#       - linux
#     env:
#       - CC=aarch64-linux-gnu-gcc
#       - CXX=aarch64-linux-gnu-g++
#     flags:
#       - -trimpath
#     ldflags:
#       - -extldflags "-lc -lrt -lpthread --static"

#   # Android ARM64
#   - id: mb2osm-android-arm64
#     binary: mb2osm
#     main: cmd/main.go
#     goarch:
#       - arm64
#     goos:
#       - android
#     env:
#       - CC=aarch64-linux-android-gcc
#       - CXX=aarch64-linux-android-g++
#     flags:
#       - -trimpath
#     ldflags:
#       - -extldflags "-lc -lrt -lpthread --static"

#   # Windows AMD64
#   - id: mb2osm-windows-amd64
#     binary: mb2osm
#     main: cmd/main.go
#     goarch:
#       - amd64
#     goos:
#       - windows
#     env:
#       - CC=x86_64-w64-mingw32-gcc
#       - CXX=x86_64-w64-mingw32-g++
#     flags:
#       - -trimpath
#       - -buildmode=exe

#   # Windows ARM64
#   - id: mb2osm-windows-arm64
#     binary: mb2osm
#     main: cmd/main.go
#     goarch:
#       - arm64
#     goos:
#       - windows
#     env:
#       - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
#       - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
#     flags:
#       - -trimpath
#       - -buildmode=exe

# archives:
#   - name_template: "mb2osm_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#     builds:
#       - mb2osm-darwin-amd64
#       - mb2osm-darwin-arm64
#       - mb2osm-linux-amd64
#       - mb2osm-linux-arm64
#       - mb2osm-windows-amd64
#     wrap_in_directory: false
#     format: tar.gz
#     # use zip for windows archives
#     format_overrides:
#       - goos: windows
#         format: zip
#     files:
#       - none*

# checksum:
#   name_template: 'checksums.txt'
# gitlab_urls:
#   use_package_registry: true
# snapshot:
#   version_template: '{{ .Tag }}-next'
# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - '^docs:'
#       - '^test:'
