archives:
  - builds:
      - mb2osm
    files:
      - none*
    format: zip
    id: w/version
    name_template: "mb2osm_archive_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    rlcp: true
    wrap_in_directory: false
builds:
- binary: mb2osm
  flags:
    - -trimpath
  id: mb2osm
  ignore:
    - goarch: "386"
      goos: windows
  main: main.go

checksum:
  name_template: 'checksums.txt'
env:
- CGO_ENABLED=0
gitlab_urls:
  use_package_registry: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
